//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BraAuto.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BraAuto.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Article with same title already exists..
        /// </summary>
        internal static string ArticleTitleExists
        {
            get
            {
                return ResourceManager.GetString("ArticleTitleExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ShowAlert.
        /// </summary>
        internal static string AlertKey
        {
            get
            {
                return ResourceManager.GetString("AlertKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, it seems that an error occurred..
        /// </summary>
        internal static string GeneralError
        {
            get
            {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email or password provided is incorrect..
        /// </summary>
        internal static string IncorrectCredentials
        {
            get
            {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provided password is incorrect..
        /// </summary>
        internal static string IncorrectPassword
        {
            get
            {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image is invalid format or too big..
        /// </summary>
        internal static string InvalidImg
        {
            get
            {
                return ResourceManager.GetString("InvalidImg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        internal static string ItemDeleted
        {
            get
            {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);

            }
        }
        /// <summary>
        ///   Looks up a localized string similar to BraAuto..
        /// </summary>
        internal static string WebsiteTitle
        {
            get
            {
                return ResourceManager.GetString("WebsiteTitle", resourceCulture);
            }
        }
    }
}